---
apiVersion: v2
name: common
version: 0.4.0
type: library
home: https://celo.org
icon: https://pbs.twimg.com/profile_images/1613170131491848195/InjXBNx9_400x400.jpg
description: Helm chart with helper templates and functions for Celo nodes.
  Import into your chart with `dependencies` and use the templates and functions
keywords:
  - celo
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
