{{- if .Values.config.envFile.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-env-file
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  .env: |
{{ .Values.config.envFile.content | indent 4 }}
{{- end }}

