{{- if and .Values.config.secretEnv (not (empty .Values.config.secretEnv)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.config.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

