---
apiVersion: v2
appVersion: "odis-signer-3.1.2"
description: Helm chart for deploying Celo ODIS signer
type: application
home: https://celo.org
icon: https://pbs.twimg.com/profile_images/1613170131491848195/InjXBNx9_400x400.jpg
name: odis-signer
sources:
  - https://celo.org
  - https://docs.celo.org
  - https://clabs.co
  - https://github.com/celo-org
keywords:
  - Celo
  - ODIS
  - Ethereum
version: 0.2.5
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
