---
apiVersion: v2
name: kona-execution-verifier
description: A Helm chart for the kona execution-verifier
type: application
version: 0.2.0
appVersion: "main"
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
sources:
  - https://github.com/celo-org/celo-kona
