---
apiVersion: v2
name: succinct-cost-estimator
description: A Helm chart for the succinct cost estimator
type: application
version: 0.1.8
appVersion: "main"
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
sources:
  - https://github.com/celo-org/op-succinct
