---
name: eigenda-proxy
apiVersion: v2
version: 0.1.0
description: https://github.com/Layr-Labs/eigenda-proxy/tree/main
home: https://clabs.co
sources:
  - https://github.com/Layr-Labs/eigenda-proxy/tree/main
  - https://celo.org
  - https://docs.celo.org
  - https://clabs.co
  - https://github.com/celo-org
keywords:
  - eigenda
  - celo
  - blockchain
  - optimism
  - rollup
  - ethereum
  - layer2
  - op-stack
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
type: application
icon: https://pbs.twimg.com/profile_images/1613170131491848195/InjXBNx9_400x400.jpg
appVersion: v1.0.0
