bootnode:
  defaultClusterIP: 10.96.12.12
replicas:
  validators: 1
  proxiesPerValidator:
    - 0
  secondaries: 0
  txNodes: 1
  txNodesPrivate: 0
geth:
  resources:
    requests:
      memory: "200Mi"
      cpu: "100m"
  txNodesIPAddressArray: []
# Insecure mnemonic for testnet
mnemonic: drum order gesture act sting mixed skirt shoot wave captain cage common antenna
  piano erupt roast settle spot extra below canoe gloom goddess neglect
genesis:
  genesisForceUrl: https://gist.githubusercontent.com/jcortejoso/224ed898e4708393d209b2848ccec21a/raw/3d95523fffcc42bdf75d962f8f7619280dce1c32/genesis.json
enableFornoIngress: false
