apiVersion: v2
name: op-ufm
description: A Helm chart for OP User Facing Monitoring
type: application
version: 0.1.0
appVersion: "op-ufm-79d95418291ba39f0a183f103893a7b7f49e0263"
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
sources:
  - https://github.com/celo-org/optimism/tree/celo7/op-ufm
