---
apiVersion: v2
name: image-annotator-webhook
type: application
icon: https://pbs.twimg.com/profile_images/1613170131491848195/InjXBNx9_400x400.jpg
version: 0.3.6
description: Deploys a kubernetes webhook to mutate podSpecs to include container images as annotations
keywords:
  - Celo
  - Blockchain
  - Ethereum
  - Proof-of-Stake
appVersion: v0.1.0
sources:
  - https://github.com/celo-org/image-annotator-webhook
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
