---
name: op-conductor
apiVersion: v2
version: 0.0.7
description: Helm chart deploying OP Conductor, a HA controller for op-node
home: https://clabs.co
sources:
  - https://github.com/Layr-Labs/eigenda-proxy/tree/main
  - https://celo.org
  - https://docs.celo.org
  - https://clabs.co
  - https://github.com/celo-org
keywords:
  - celo
  - blockchain
  - optimism
  - rollup
  - ethereum
  - layer2
  - op-stack
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
type: application
icon: https://pbs.twimg.com/profile_images/1613170131491848195/InjXBNx9_400x400.jpg
appVersion: v1.8.0
