---
# Execution-layer sync: restore from snapshot, sync via p2p
snapshot:
  enabled: true

op-geth:
  config:
    syncmode: full
  init:
    genesis:
      enabled: false

op-node:
  config:
    syncmode: execution-layer
