apiVersion: apps/v1
kind: Deployment
metadata:
  name: "notifications-webhooks-worker-{{ include "safe-transaction-service-helm.fullname" . }}"
  labels:
    {{- include "safe-transaction-service-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifications-webhooks-worker
spec:
  replicas: {{ default .Values.replicaCount .Values.notificationsWebhooksWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "safe-transaction-service-helm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: notifications-webhooks-worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "safe-transaction-service-helm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: notifications-webhooks-worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "safe-transaction-service-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: notifications-webhooks-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["docker/web/celery/worker/run.sh"]
          env:
            - name: WORKER_QUEUES
              value: "contracts,tokens"
            - name: DATABASE_URL
              value: postgres://postgres:{{ .Values.global.postgresql.auth.postgresPassword }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.global.postgresql.auth.database }}
            - name: ETHEREUM_NODE_URL
              value: {{ .Values.env.ethereumNodeUrl }}
            - name: REDIS_URL
              value: redis://:{{ .Values.global.redis.password }}@{{ .Release.Name }}-redis-master:6379/0
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.local
            - name: DJANGO_SECRET_KEY
              value: "{{ .Values.env.djangoSecretKey }}"
            - name: CELERY_BROKER_URL
              value: amqp://user:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq/
          resources:
            {{- if .Values.notificationsWebhooksWorker.resources }}
              {{- toYaml .Values.notificationsWebhooksWorker.resources | nindent 12 }}
            {{- else }}
              {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
