---
secrets:
  # Private Key for the proposer. Either provide the secret name and key or the value directly. If value is not empty, it will have precedence over the secret.
  privateKey:
    value: 0x0000000000000000000000000000000000000000000000000000000000000001
    secretName: private-key-secret
    secretKey: privateKeyKey
  # L1 URL for the proposer. Either provide the secret name and key or the value directly. If value is not empty, it will have precedence over the secret.
  l1Url:
    value: https://ethereum-holesky-rpc.publicnode.com
extraArgs:
  - --wait-node-sync=true
config:
  l2Url: http://op-node:8545
  rollupUrl: http://op-node:9545
