---
apiVersion: v2
name: op-succinct
description: A Helm chart for op-succinct proposer and challenger
type: application
version: 1.1.0
appVersion: 1.0.2
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
sources:
  - https://github.com/celo-org/op-succinct
