---
secrets:
  # Private Key for the proposer. Either provide the secret name and key or the value directly. If value is not empty, it will have precedence over the secret.
  privateKey:
    secretName: private-key-secret
    secretKey: privateKeyKey
  # L1 URL for the proposer. Either provide the secret name and key or the value directly. If value is not empty, it will have precedence over the secret.
  l1Url:
    value: https://ethereum-holesky-rpc.publicnode.com
